version: '2'
services:
  mysql:
    volumes:
     - belun_mysql_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
  web:
    image: wordpress
    ports:
      - "8088:80"
    links:
      - mysql
    volumes:
      - belun_wordpress:/var/www/html
      
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret

volumes:
  belun_mysql_db:
  belun_wordpress:
