mysql:
  image: belun/mysql
  volumes_from:
    - belun_mysql_data
  command: mysqld_safe
web:
  image: wordpress
  container_name: wpbelun
  ports:
    - "8088:80"
  links:
    - mysql
  volumes_from:
    - belun_wordpress_data
  environment:
    WORDPRESS_DB_USER: "belun"
    WORDPRESS_DB_PASSWORD: "secret"


